server:
  port: 8080

spring:
  application:
    name: youtube-app
  
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  level:
    com.youtube.app: DEBUG
    org.springframework.web: DEBUG